version: '3.1'

services:
  mongodb:
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    container_name: mongodb
  
  fastify:
    image: project2:1.2
    ports:
      - '3000:3000'
    container_name: project2
    depends_on:
      - mongodb
    environment:
      MONGO_USERNAME: ${MONGO_USERNAME}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_HOSTNAME: ${MONGO_HOSTNAME}


